HRM/urls.py
from django.contrib import admin
from django.urls import path, include
from payroll import views
from userapp import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('payroll/', include("payroll.urls", namespace="payroll")),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('', include("userapp.urls", namespace="userapp")),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
]

payroll/urls.py
from django.urls import path, re_path, reverse
from . import views
from django.contrib import admin

app_name = 'payroll'

urlpatterns = [
path('employee_list',views.EmployeeListView.as_view(),name='employee_list'),
path('table/',views.table,name='table'),

path('employee/<str:pk>/',views.EmployeeDetailView.as_view(),name='employee_detail'),
path('employee_create/',views.EmployeeCreateView.as_view(),name='employee_create'),
path('employee/update/<str:pk>/',views.EmployeeUpdateView.as_view(),name='employee_update'),
path('upload-employee-csv/', views.employee_upload, name="employee_upload"),
path('employee/delete/<str:pk>/',views.EmployeeDeleteView.as_view(),name='employee_delete'),

path('department_create/',views.DepartmentCreateView.as_view(),name='department_create'),
path('department_list',views.DepartmentListView.as_view(),name='department_list'),
path('department/<int:pk>/',views.DepartmentDetailView.as_view(),name='department_detail'),
path('department/update/<int:pk>/',views.DepartmentUpdateView.as_view(),name='department_update'),
path('department/delete/<int:pk>/',views.DepartmentDeleteView.as_view(),name='department_delete'),

path('payslip_list',views.PayslipListView.as_view(),name='payslip_list'),
path('payslip/<int:pk>/',views.PayslipDetailView.as_view(),name='payslip_detail'),
path('payslip_create/',views.PayslipCreateView.as_view(),name='payslip_create'),
path('payslip/update/<int:pk>/',views.PayslipUpdateView.as_view(),name='payslip_update'),
path('upload-payslip-csv/', views.paydetail_upload, name="paydetail_upload"),
path('upload-clinical-csv/', views.clinical_upload, name="clinical_upload"),
path('payslip/delete/<int:pk>/',views.PayslipDeleteView.as_view(),name='payslip_delete'),

path('additional_create/',views.AdditionalCreateView.as_view(),name='additional_create'),
path('additional_list',views.AdditionalListView.as_view(),name='additional_list'),
path('additional/<int:pk>/',views.AdditionalDetailView.as_view(),name='additional_detail'),
path('additional/update/<int:pk>/',views.AdditionalUpdateView.as_view(),name='additional_update'),
path('additional/delete/<int:pk>/',views.AdditionalDeleteView.as_view(),name='additional_delete'),
path('upload-additional_pay-csv/', views.additional_upload, name="additional_upload"),


path('deduction_create/',views.DeductionCreateView.as_view(),name='deduction_create'),
path('deduction_list',views.DeductionListView.as_view(),name='deduction_list'),
path('deduction/<int:pk>/',views.DeductionDetailView.as_view(),name='deduction_detail'),
path('deduction/update/<int:pk>/',views.DeductionUpdateView.as_view(),name='deduction_update'),
path('deduction/delete/<int:pk>/',views.DeductionDeleteView.as_view(),name='deduction_delete'),
path('upload-deduction_pay-csv/', views.deduction_upload, name="deduction_upload"),

path('process_salary/',views.ProcessSalaryListView.as_view(),name='process_salary_list'),
path('payroll_register/',views.PayrollRegisterView.as_view(),name='payroll_register'),
path('process_salary/<int:pk>/',views.ProcessSalaryDetailView.as_view(),name='process_salary_detail'),
path('process_salary_create/',views.ProcessSalaryCreateView.as_view(),name='process_salary_create'),
path('process_salary/update/<int:pk>/',views.ProcessSalaryUpdateView.as_view(),name='process_salary_update'),
path('process_salary/delete/<int:pk>/',views.ProcessSalaryDeleteView.as_view(),name='process_salary_delete'),

path('salary_report/',views.SalaryReport.as_view(),name='salary_report_list'),
path('report_detail/<int:pk>/',views.ReportDetailView.as_view(),name='report_detail'),
path('report_detail_view/<int:pk>/',views.ReportDetailView_Revised.as_view(),name='report_detail_view'),

path('thanks/', views.ThanksPage.as_view(), name="thanks"),

path('employee_payslip/<int:pk>/',views.EmployeePayslip,name='employee_payslip'),
path('salary_process_btn/<int:pk>/',views.update_ps, name='update_ps'),
path('empdeplist/<int:pk>/',views.ListofEmpInDep, name="empdeplist"),

path('payroll_list/',views.ListofPayroll, name="payroll_list"),
path('payroll_detail/<int:pk>/',views.DetailofPayroll, name="payroll_detail"),

path('payroll_report/<slug:payrollid>/<slug:empid>/',views.emppayslip,name='payroll_report'),
path('payroll_report_view/<slug:payrollid>/<slug:empid>',views.emppayslip_view,name='payroll_report_view'),

path('excle/<int:pk>',views.load_workbook, name="excle"),
path('bank_excle/<int:pk>',views.load_workbook_bank, name="bank_excle"),
path('lulu_excle/<int:pk>',views.load_workbook_lulu, name="lulu_excle"),

path ('pdf/<slug:pk>/<slug:empid>', views.payslipPdf, name='pdf'),
path ('pays_detail_pdf/<int:pk>/', views.PaysDetailsPDFView, name='pays_detail_pdf_list'),
path ('pay_detail_list_pdf', views.PayDetailListPDF, name='pay_detail_list_pdf'),
path ('PDFdeduction', views.DeductionsPDFView.as_view(), name='pdf_deduction'),
path ('PDFadditional', views.AdditionalPDFView.as_view(), name='pdf_additional'),

path ('salary_additional/<int:pk>/',views.SalaryAdditional, name="salary_additional"),
path ('salary_deductions/<int:pk>/',views.SalaryDeductions, name="salary_deductions"),
path ('employee_timesheet/<int:pk>/',views.EmpTimesheet, name="emp_timesheet"),

path ('timesheet_list/',views.EmployeeTimesheet.as_view(), name="timesheet_list"),
path('timesheet_create/',views.EmployeeTimesheetCreateView.as_view(),name='timesheet_create'),
path('timesheet/update/<int:pk>/',views.EmployeeTimesheetUpdateView.as_view(),name='timesheet_update'),
path('timesheet/delete/<int:pk>/',views.EmployeeTimesheetDeleteView.as_view(),name='timesheet_delete'),
path('upload-timesheet-csv/', views.timesheet_upload, name="timesheet_upload"),

path ('process_salary_additional/<int:pk>/',views.ProcessSalaryAdditional, name="process_salary_additional"),
path ('process_salary_deductions/<int:pk>/',views.ProcessSalaryDeductions, name="process_salary_deductions"),
path ('process_salary_timesheet/<int:pk>/',views.ProcessSalaryTimesheet, name="process_salary_timesheet"),
path ('process_salary_master/<int:pk>/',views.ProcessSalaryMaster, name="process_salary_master"),
path ('process_salary_paydetails/<int:pk>/',views.ProcessSalaryPayDetails, name="process_salary_paydetails"),
path ('process_salary_bank/<int:pk>/',views.ProcessSalaryBank, name="process_salary_bank"),
path ('process_salary_lulu/<int:pk>/',views.ProcessSalaryLulu, name="process_salary_lulu"),

path ('salary_record/', views.SalaryRecord, name='salary_record'),
path ('salary_record_detail/<slug:empid>', views.SalaryRecordDetail, name='salary_record_detail'),

path('emailpdf/<str:pk>/<str:empid>',views.singleEmail,name='emailpdf'),
path('email/<str:pk>/',views.email,name='email'),
path('downloadAll/<str:pk>/',views.downloadAll,name='downloadAll'),
path('displayPdf/<str:pk>/<str:empid>',views.DisplayPdf.as_view(),name='displayPdf'),

path('delete_all_timesheet/',views.delete_everything, name='delete_everything'),

path('hr_records/',views.hr_records, name='hr_records'),

path('labour_contract_list',views.LabourContractListView.as_view(),name='labour_contract_list'),
path('labour_contract_print',views.LabourContractPrint, name='labour_contract_print'),
path('labour_contract_detail/<str:pk>/',views.LabourContractDetailView.as_view(),name='labour_contract_detail'),
path('labour_contract_create/',views.LabourContractCreateView.as_view(),name='labour_contract_create'),
path('contract/update/<str:pk>/',views.LabourContractUpdateView.as_view(),name='contract_update'),
path('contract/delete/<str:pk>/',views.LabourContractDeleteView.as_view(),name='labour_contract_delete'),

path('work_permit_list',views.WorkPermitListView.as_view(),name='work_permit_list'),
path('work_permit_print',views.WorkPermitPrint, name='work_permit_print'),
path('work_permit_detail/<str:pk>/',views.WorkPermitDetailView.as_view(),name='work_permit_detail'),
path('work_permit/update/<str:pk>/',views.WorkPermitUpdateView.as_view(),name='work_permit_update'),
path('work_permit/delete/<str:pk>/',views.WorkPermitDeleteView.as_view(),name='work_permit_delete'),
path('work_permit_create/',views.WorkPermitCreateView.as_view(),name='work_permit_create'),

path('eid_collect_list',views.EidCollectListView.as_view(),name='eid_collect_list'),
path('eid_collect_print',views.EidCollectPrint, name='eid_collect_print'),
path('eid_collect_detail/<str:pk>/',views.EidCollectDetailView.as_view(),name='eid_collect_detail'),
path('eid_collect/update/<str:pk>/',views.EidCollectUpdateView.as_view(),name='eid_collect_update'),
path('eid_collect/delete/<str:pk>/',views.EidCollectDeleteView.as_view(),name='eid_collect_delete'),
path('eid_collect_create/',views.EidCollectCreateView.as_view(),name='eid_collect_create'),

path('new_eid_list',views.NewEidListView.as_view(),name='new_eid_list'),
path('new_eid_print',views.NewEidPrint, name='new_eid_print'),
path('new_eid_detail/<str:pk>/',views.NewEidDetailView.as_view(),name='new_eid_detail'),
path('new_eid/update/<str:pk>/',views.NewEidUpdateView.as_view(),name='new_eid_update'),
path('new_eid/delete/<str:pk>/',views.NewEidDeleteView.as_view(),name='new_eid_delete'),
path('new_eid_create/',views.NewEidCreateView.as_view(),name='new_eid_create'),

path('upload-New-EID-csv/', views.neweid_upload, name="neweid_upload"),
path('upload-labour-contract-csv/', views.labourcontract_upload, name="labour_contract_upload"),
path('update-labour-contract-csv/', views.passport_update, name="passport_update"),

path('p_contract_sign',views.p_contract_sign, name='p_contract_sign'),
path('p_wp_sign',views.p_wp_sign, name='p_wp_sign'),
path('p_eid_collect',views.p_eid_collect, name='p_eid_collect'),
path('p_p_collect',views.p_p_collect, name='p_p_collect'),


path('p_passport_collect',views.p_passport_collect, name='p_passport_collect'),
path('p_visa_medical',views.p_visa_medical, name='p_visa_medical'),

path('passport_return_list',views.PassportReturnListView.as_view(),name='p_return_list'),

userapp/urls.py
from django.urls import path, re_path, reverse
from . import views
from django.contrib import admin

app_name = 'userapp'

urlpatterns = [
    path('',views.IndexView,name='index'),
    path('profile/',views.ProfileView,name='profile'),
    path('department_list',views.DepartmentListView.as_view(),name='department_list'),
    path('empdeplist/<int:pk>/',views.ListofEmpInDep, name="empdeplist"),
    path('employee/update/',views.EmployeeUpdateView.as_view(),name='employee_update'),
]

userapp/models.py
from django.db import models
from django.contrib import admin
from payroll.models import Employee, Payslip, Department, CostCenter, Timesheet, Report, Additionalpay, Deduction, ReportTimesheet
# Create your models here.

userapp/forms.py
from .models import Department, Employee, Payslip, Additionalpay, Deduction, Timesheet
from django.forms import ModelForm, Form
from django import forms
from . import models

class EmployeeForm(ModelForm):
    class Meta:
        model= Employee
        fields = '__all__'
        exclude = ('employee_status',)
        unique_together = [("first_name", "last_name" )]
        widgets = {
            'DOB':forms.DateInput(attrs={'type':'date'}),
            'joining_date':forms.DateInput(attrs={'type':'date'})
        }

    # def __init__(self, *args, **kwargs):
    #      super().__init__(*args, **kwargs)
    #      for field in self.fields:
    #          self.fields[field].widget.attrs.update({'class':'form-control'})

userapp/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from django.urls import reverse_lazy
from django.views.generic import (View, ListView, TemplateView, DetailView, CreateView, UpdateView, DeleteView)
from . import models
from . forms import EmployeeForm
import re, os
from datetime import date
from django.db.models import Sum, Avg, Max, Count, Min
from django.db.models.functions import Coalesce
from django.db.models import Value
from openpyxl import Workbook
from openpyxl.styles import colors, Color, Border, Side, PatternFill, Font, GradientFill, Alignment
from os import path
from django.http import HttpResponse
from easy_pdf.views import PDFTemplateView, PDFTemplateResponseMixin, TemplateResponseMixin
from easy_pdf.rendering import render_to_pdf_response
from django.contrib import messages
import csv, io
from django.core.mail import send_mail, EmailMessage
from django.conf import settings
from django.http import FileResponse
from django.http import Http404
from django.views.generic.detail import BaseDetailView
from django.contrib import admin
from django.contrib.auth.models import User
from django.contrib.auth.admin import UserAdmin

# Create your views here.

def IndexView(request):
    return render(request, 'userapp/index.html')

def ProfileView(request):
    emp = models.Employee.objects.get(email=request.user.email)
    payslip = models.Payslip.objects.get(employee_id=emp.employee_id)
    record = models.Report.objects.filter(employee_id=emp.employee_id)
    add = models.Additionalpay.objects.filter(payslip__employee_id=emp.employee_id)
    deduction = models.Deduction.objects.filter(payslip__employee_id=emp.employee_id)
    timesheet = models.ReportTimesheet.objects.filter(report__employee_id=emp.employee_id)
    empid = emp.employee_id

    return render(request, 'userapp/user_profile.html',
        {'record':record,
        'empid':empid,
        'add':add,
        'deduction':deduction,
        'timesheet':timesheet,
        'emp':emp,
        'payslip':payslip
        })

class DepartmentListView(ListView):
    template_name = 'userapp/department_list.html'
    context_object_name = 'department_list'
    model = models.Department

    def get_context_data(self, *args, **kwargs):
        context = super(DepartmentListView,self).get_context_data(*args,**kwargs)
        dep_list = context['department_list']
        empData = []
        for dep in dep_list:
            total_em = models.Employee.objects.filter(department=dep).count()
            department_head = None
            try:
                department_head = models.Employee.objects.get(department_head=True, department=dep)
            except models.Employee.DoesNotExist:
                department_head = "-"
            total_emp = total_em or 0
            empData.append([dep,total_emp,department_head])
        context['Data'] = empData

        return (context)

def ListofEmpInDep(request, pk):
    data = models.Department.objects.get(pk=pk)
    list_employee = models.Employee.objects.filter(department=data)

    return render(request,'userapp/empdeplist.html',
        {'list_employee':list_employee,
        'data': data,
        })

def SalaryRecordDetail(request,empid ):
    fullname = models.Employee.objects.get(employee_id=empid)
    record = models.Report.objects.filter(employee_id=empid)
    add = models.Additionalpays.objects.filter(report__employee_id=empid)
    deduction = models.Deductions.objects.filter(report__employee_id=empid)
    timesheet = models.ReportTimesheet.objects.filter(report__employee_id=empid)
    data = []
    total_lwop = 0
    total_gross = 0
    total_add = 0
    total_ded = 0
    total_net = 0

    for r in record:
        empAdd = models.Additionalpays.objects.filter(report=r).aggregate(Sum('amount'))['amount__sum']
        empDed = models.Deductions.objects.filter(report=r).aggregate(Sum('amount'))['amount__sum']
        empAdd = empAdd or 0
        empDed = empDed or 0
        empAdd = (round(empAdd,2))
        empDed = (round(empDed,2))
        gross = r.gross_pay - r.lowp_deduction
        net= gross + empAdd - empDed

        total_lwop += r.lowp_deduction
        total_gross += gross
        total_add += empAdd
        total_ded += empDed
        total_net += net

        data.append([r,empAdd,empDed,net,gross])



    return render(request, 'userapp/salary_record_detail.html',
        {'record':record,
        'empid':empid,
        'add':add,
        'deduction':deduction,
        'timesheet':timesheet,
        'fullname':fullname,
        'data':data,
        'total_lwop':total_lwop,
        'total_gross': total_gross,
        "total_add": total_add,
        'total_ded': total_ded,
        'total_net': total_net,
        })


class EmployeeUpdateView(UpdateView):
    model = models.Employee
    form_class = EmployeeForm
    template_name='userapp/employee_update.html'

userapp/templates/userapp/department_list.html
{% extends "base.html" %}
{% block content %}
{% load humanize %}
<p></p>

<div class="jumbotron">
  <h2 class="display-4"> Department list</h2>

  <table class="table table-hover" id="table_id">
    <thead>
      <tr>
        <th scope="col">SN.</th>
        <th scope="col">Department Name</th>
        <th scope="col">Department Head</th>
        <th scope="col">No. of Employee</th>
      </tr>
    </thead>
    <tbody>
      {% for department in Data %}
      <tr>
        <td scope="row">{{ forloop.counter }}</td>
        <td><a href="{% url 'userapp:empdeplist' pk=department.0.pk %}">{{department.0.department}} </a> </td>
        <td> {{department.2}}</td>
        <td>{{department.1}}</td>
      {% endfor %}
    </tbody>
  </table>
  <a class="btn btn-outline-danger btn-lg mt-3" href="{% url 'userapp:profile' %}" role="button">Back to Profile</a>
</div>
{% endblock %}
{% block script %}
<script>
  $(document).ready(function() {
    $('#table_id').DataTable();
  });
</script>
{% endblock %}

userapp/templates/userapp/empdeplist.html
{% extends "base.html" %}
{% block content %}
{% load humanize %}
<p></p>

<div class="jumbotron">
  <h2 class="display-4"> Employee list in {{data}} </h2>

  <table class="table table-hover" id="table_id">
    <thead>
      <tr>
        <th scope="col">SN.</th>
        <th> Name of Employee</th>
        <th> Degination</th>
        <th> Phone</th>
        <th> Email</th>
      </tr>
    </thead>
    <tbody>

      {% for emp in list_employee %}
      <tr>
        <td scope="row">{{ forloop.counter }}</td>
        <td> {{emp}} </td>
        <td> {{emp.designation}} </td>
        <td> {{emp.phone}} </td>
        <td> {{emp.email}} </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <a class="btn btn-outline-danger btn-lg mt-3" href="{% url 'userapp:department_list' %}" role="button">Back to department list</a>

</div>

{% endblock %}
{% block script %}
<script>
  $(document).ready(function() {
    $('#table_id').DataTable();
  });
</script>
{% endblock %}

userapp/templates/userapp/employee_update.html
{% extends "base.html" %}
  {% load static %}
  {% block content %}

  <div class="jumbotron">
    <div class="col-md-8 offset-2">
      <h1 class="display-4">Update employee</h1>
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-outline-success btn-lg" name="submit" value="Update">
        <a class="btn btn-outline-danger btn-lg" href="{% url 'payroll:employee_list' %}" role="button">Back to employee list</a>
      </form>
   </div>
  </div>
{% endblock %}

userapp/templates/userapp/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<div class="jumbotron shadow-sm p-3 mb-5 rounded mt-3">
  <h5> Hi, {{user.username }} </h5>
  <p> {{ user.email }}</p>
</div>
{% else %}
<div class="jumbotron shadow-sm p-3 mb-5 rounded mt-3">
  <h2 class="display-4"> Welcome </h2>
     <p> </p><strong> Please login to get access to your profile. <a href="{% url 'accounts:login' %}" class="btn btn-simple"> Login <i class="fas fa-user"></i></a> </strong></a> <hr>
    
</div>
{% endif %}
{% endblock %}
{% block script %}
<script>
</script>
{% endblock %}

userapp/templates/userapp/user_profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% if user.is_staff %}
<div class="jumbotron shadow-sm p-3 mb-5 rounded mt-3">
  <h5> Hi, {{user.username }} </h5>
  <div class="row ">
    <div class="col-sm-12">
      <ul class="list-group mb-2">
          <li class="list-group-item"> <img src="{{emp.img.url}}" width="200" alt="">
            <h4>{{emp.first_name }} {{emp.last_name }} <a href="#"> <small> <i class="fas fa-edit mr-2"> </i></small></a></h4>
          </li>
        <div class="accordion" id="accordionExample">
          <div class="card">
            <div class="card-header" id="headingOne">
              <h5 class="mb-0">
                <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                  Employee Additional Information
                </button>
              </h5>
            </div>
            <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
          <div class="card-body">
            <li class="list-group-item">{{emp.phone }}</li>
            <li class="list-group-item">{{emp.email }}</li>
            <li class="list-group-item">{{emp.department }} / {{payslip_detail.employee.designation }}</li>
            <li class="list-group-item">{{emp.uae_address }}</li>
          </div>
          </div>
        </div>
        <div class="card">
          <div class="card-header" id="headingTwo">
            <h5 class="mb-0">
              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                Employee salary component
              </button>
            </h5>
          </div>
          <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
            <div class="card-body">
              <li class="list-group-item">Basic salary : {{payslip.basic_salary }}</li>
              <li class="list-group-item"> Housing Allowance : {{payslip.housing_allowance }}</li>
              <li class="list-group-item"> Transportation allowance : {{payslip.transportation_allowance }}</li>
              <li class="list-group-item"> Other Allowance : {{payslip.other}}</li>            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-header" id="headingThree">
            <h5 class="mb-0">
              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                Employee bank information
              </button>
            </h5>
          </div>
          <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
            <div class="card-body">
              <li class="list-group-item">Bank Detail : {{payslip.mode_of_payment }}</li>
              <li class="list-group-item">Bank Ac No. : {{payslip.bank_ac }}</li>
              <li class="list-group-item">Employee Unique ID : {{payslip.employee_unique }}</li>
              <li class="list-group-item">Agent ID : {{payslip.agent_id }}</li>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-header" id="headingFour">
            <h5 class="mb-0">
              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                Employee Lulu Exchange information
              </button>
            </h5>
          </div>
          <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordionExample">
            <div class="card-body">
              <li class="list-group-item">Bank Ac No. : {{payslip.bank_ac }}</li>
              <li class="list-group-item">Work permit 8 digits : {{payslip.work_permit_8_digits }}</li>
              <li class="list-group-item">Personal no 14 digits : {{payslip.personal_no_14_digits }}</li>
              <li class="list-group-item">Bank name & routing no. : {{payslip.bank_name_routing }}</li>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-header" id="headingFive">
            <h5 class="mb-0">
              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                My Pending Deductions
              </button>
            </h5>
          </div>
          <div id="collapseFive" class="collapse" aria-labelledby="headingFive" data-parent="#accordionExample">
            <div class="card-body">
              <h3>Deduction:</h3>
                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">S.N.</th>
                      <th scope="col">Particular</th>
                      <th scope="col">Label</th>
                      <th scope="col">Amount</th>
                      <th scope="col">Occurs</th>
                      <th scope="col">Starts</th>
                      <th scope="col">Ends</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for ded in deduction %}

                    <tr>
                      <td scope="row">{{ forloop.counter }}</td>
                      <td>{{ded.deduction}}</td>
                      <td>{{ded.deduction_label}}</td>
                      <td>{{ded.amount}}</td>
                      <td>{{ded.occur}}</td>
                      <td>{{ded.start_date | date:'Y-m-d' | default_if_none:''}}</td>
                      <td>{{ded.end_date | date:'Y-m-d' | default_if_none:''}}</td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
            </div>
          </div>
          <li> <a href="{% url 'payroll:salary_record_detail' empid=emp.employee_id %}" class="btn btn-simple ml-3 mt-3 mb-3">My Salary / Timesheet Records </a> </li>
          <li> <a href="{% url 'userapp:department_list' %}" class="btn btn-simple ml-3 mb-3">View Company Departments & Employee </a></li>
        </div>
      </div>
      </ul>
    </div>
  </div>
</div>
{% elif user.is_authenticated %}
<div class="jumbotron shadow-sm p-3 mb-5 rounded mt-3">
  <h2 class="display-4"> Welcome </h2>
  <p> Sorry {{user.username }} you cannot access other features.. </p>
</div>
{% else %}
<div class="jumbotron shadow-sm p-3 mb-5 rounded mt-3">
  <h2 class="display-4"> Welcome </h2>
    <a href="{% url 'accounts:login' %}" class="btn btn-simple">Please login to get access to your profile. Login <i class="fas fa-user"></i></a>
</div>
{% endif %}
{% endblock %}
{% block script %}
<script>
</script>
{% endblock %}