HRM/urls.py
from django.contrib import admin
from django.urls import path, include
from payroll import views
from userapp import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('payroll/', include("payroll.urls", namespace="payroll")),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('', include("userapp.urls", namespace="userapp")),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payroll/urls.py
from django.urls import path, re_path, reverse
from . import views
from django.contrib import admin

app_name = 'payroll'

urlpatterns = [
path('employee_list',views.EmployeeListView.as_view(),name='employee_list'),
path('table/',views.table,name='table'),

path('employee/<str:pk>/',views.EmployeeDetailView.as_view(),name='employee_detail'),
path('employee_create/',views.EmployeeCreateView.as_view(),name='employee_create'),
path('employee/update/<str:pk>/',views.EmployeeUpdateView.as_view(),name='employee_update'),
path('upload-employee-csv/', views.employee_upload, name="employee_upload"),
path('employee/delete/<str:pk>/',views.EmployeeDeleteView.as_view(),name='employee_delete'),

path('department_create/',views.DepartmentCreateView.as_view(),name='department_create'),
path('department_list',views.DepartmentListView.as_view(),name='department_list'),
path('department/<int:pk>/',views.DepartmentDetailView.as_view(),name='department_detail'),
path('department/update/<int:pk>/',views.DepartmentUpdateView.as_view(),name='department_update'),
path('department/delete/<int:pk>/',views.DepartmentDeleteView.as_view(),name='department_delete'),

path('payslip_list',views.PayslipListView.as_view(),name='payslip_list'),
path('payslip/<int:pk>/',views.PayslipDetailView.as_view(),name='payslip_detail'),
path('payslip_create/',views.PayslipCreateView.as_view(),name='payslip_create'),
path('payslip/update/<int:pk>/',views.PayslipUpdateView.as_view(),name='payslip_update'),
path('upload-payslip-csv/', views.paydetail_upload, name="paydetail_upload"),
path('upload-clinical-csv/', views.clinical_upload, name="clinical_upload"),
path('payslip/delete/<int:pk>/',views.PayslipDeleteView.as_view(),name='payslip_delete'),

path('additional_create/',views.AdditionalCreateView.as_view(),name='additional_create'),
path('additional_list',views.AdditionalListView.as_view(),name='additional_list'),
path('additional/<int:pk>/',views.AdditionalDetailView.as_view(),name='additional_detail'),
path('additional/update/<int:pk>/',views.AdditionalUpdateView.as_view(),name='additional_update'),
path('additional/delete/<int:pk>/',views.AdditionalDeleteView.as_view(),name='additional_delete'),
path('upload-additional_pay-csv/', views.additional_upload, name="additional_upload"),


path('deduction_create/',views.DeductionCreateView.as_view(),name='deduction_create'),
path('deduction_list',views.DeductionListView.as_view(),name='deduction_list'),
path('deduction/<int:pk>/',views.DeductionDetailView.as_view(),name='deduction_detail'),
path('deduction/update/<int:pk>/',views.DeductionUpdateView.as_view(),name='deduction_update'),
path('deduction/delete/<int:pk>/',views.DeductionDeleteView.as_view(),name='deduction_delete'),
path('upload-deduction_pay-csv/', views.deduction_upload, name="deduction_upload"),

path('process_salary/',views.ProcessSalaryListView.as_view(),name='process_salary_list'),
path('payroll_register/',views.PayrollRegisterView.as_view(),name='payroll_register'),
path('process_salary/<int:pk>/',views.ProcessSalaryDetailView.as_view(),name='process_salary_detail'),
path('process_salary_create/',views.ProcessSalaryCreateView.as_view(),name='process_salary_create'),
path('process_salary/update/<int:pk>/',views.ProcessSalaryUpdateView.as_view(),name='process_salary_update'),
path('process_salary/delete/<int:pk>/',views.ProcessSalaryDeleteView.as_view(),name='process_salary_delete'),

path('salary_report/',views.SalaryReport.as_view(),name='salary_report_list'),
path('report_detail/<int:pk>/',views.ReportDetailView.as_view(),name='report_detail'),
path('report_detail_view/<int:pk>/',views.ReportDetailView_Revised.as_view(),name='report_detail_view'),

path('thanks/', views.ThanksPage.as_view(), name="thanks"),

path('employee_payslip/<int:pk>/',views.EmployeePayslip,name='employee_payslip'),
path('salary_process_btn/<int:pk>/',views.update_ps, name='update_ps'),
path('empdeplist/<int:pk>/',views.ListofEmpInDep, name="empdeplist"),

path('payroll_list/',views.ListofPayroll, name="payroll_list"),
path('payroll_detail/<int:pk>/',views.DetailofPayroll, name="payroll_detail"),

path('payroll_report/<slug:payrollid>/<slug:empid>/',views.emppayslip,name='payroll_report'),
path('payroll_report_view/<slug:payrollid>/<slug:empid>',views.emppayslip_view,name='payroll_report_view'),

path('excle/<int:pk>',views.load_workbook, name="excle"),
path('bank_excle/<int:pk>',views.load_workbook_bank, name="bank_excle"),
path('lulu_excle/<int:pk>',views.load_workbook_lulu, name="lulu_excle"),

path ('pdf/<slug:pk>/<slug:empid>', views.payslipPdf, name='pdf'),
path ('pays_detail_pdf/<int:pk>/', views.PaysDetailsPDFView, name='pays_detail_pdf_list'),
path ('pay_detail_list_pdf', views.PayDetailListPDF, name='pay_detail_list_pdf'),
path ('PDFdeduction', views.DeductionsPDFView.as_view(), name='pdf_deduction'),
path ('PDFadditional', views.AdditionalPDFView.as_view(), name='pdf_additional'),

path ('salary_additional/<int:pk>/',views.SalaryAdditional, name="salary_additional"),
path ('salary_deductions/<int:pk>/',views.SalaryDeductions, name="salary_deductions"),
path ('employee_timesheet/<int:pk>/',views.EmpTimesheet, name="emp_timesheet"),

path ('timesheet_list/',views.EmployeeTimesheet.as_view(), name="timesheet_list"),
path('timesheet_create/',views.EmployeeTimesheetCreateView.as_view(),name='timesheet_create'),
path('timesheet/update/<int:pk>/',views.EmployeeTimesheetUpdateView.as_view(),name='timesheet_update'),
path('timesheet/delete/<int:pk>/',views.EmployeeTimesheetDeleteView.as_view(),name='timesheet_delete'),
path('upload-timesheet-csv/', views.timesheet_upload, name="timesheet_upload"),

path ('process_salary_additional/<int:pk>/',views.ProcessSalaryAdditional, name="process_salary_additional"),
path ('process_salary_deductions/<int:pk>/',views.ProcessSalaryDeductions, name="process_salary_deductions"),
path ('process_salary_timesheet/<int:pk>/',views.ProcessSalaryTimesheet, name="process_salary_timesheet"),
path ('process_salary_master/<int:pk>/',views.ProcessSalaryMaster, name="process_salary_master"),
path ('process_salary_paydetails/<int:pk>/',views.ProcessSalaryPayDetails, name="process_salary_paydetails"),
path ('process_salary_bank/<int:pk>/',views.ProcessSalaryBank, name="process_salary_bank"),
path ('process_salary_lulu/<int:pk>/',views.ProcessSalaryLulu, name="process_salary_lulu"),

path ('salary_record/', views.SalaryRecord, name='salary_record'),
path ('salary_record_detail/<slug:empid>', views.SalaryRecordDetail, name='salary_record_detail'),

path('emailpdf/<str:pk>/<str:empid>',views.singleEmail,name='emailpdf'),
path('email/<str:pk>/',views.email,name='email'),
path('downloadAll/<str:pk>/',views.downloadAll,name='downloadAll'),
path('displayPdf/<str:pk>/<str:empid>',views.DisplayPdf.as_view(),name='displayPdf'),

path('delete_all_timesheet/',views.delete_everything, name='delete_everything'),

path('hr_records/',views.hr_records, name='hr_records'),

path('labour_contract_list',views.LabourContractListView.as_view(),name='labour_contract_list'),
path('labour_contract_print',views.LabourContractPrint, name='labour_contract_print'),
path('labour_contract_detail/<str:pk>/',views.LabourContractDetailView.as_view(),name='labour_contract_detail'),
path('labour_contract_create/',views.LabourContractCreateView.as_view(),name='labour_contract_create'),
path('contract/update/<str:pk>/',views.LabourContractUpdateView.as_view(),name='contract_update'),
path('contract/delete/<str:pk>/',views.LabourContractDeleteView.as_view(),name='labour_contract_delete'),

path('work_permit_list',views.WorkPermitListView.as_view(),name='work_permit_list'),
path('work_permit_print',views.WorkPermitPrint, name='work_permit_print'),
path('work_permit_detail/<str:pk>/',views.WorkPermitDetailView.as_view(),name='work_permit_detail'),
path('work_permit/update/<str:pk>/',views.WorkPermitUpdateView.as_view(),name='work_permit_update'),
path('work_permit/delete/<str:pk>/',views.WorkPermitDeleteView.as_view(),name='work_permit_delete'),
path('work_permit_create/',views.WorkPermitCreateView.as_view(),name='work_permit_create'),

path('eid_collect_list',views.EidCollectListView.as_view(),name='eid_collect_list'),
path('eid_collect_print',views.EidCollectPrint, name='eid_collect_print'),
path('eid_collect_detail/<str:pk>/',views.EidCollectDetailView.as_view(),name='eid_collect_detail'),
path('eid_collect/update/<str:pk>/',views.EidCollectUpdateView.as_view(),name='eid_collect_update'),
path('eid_collect/delete/<str:pk>/',views.EidCollectDeleteView.as_view(),name='eid_collect_delete'),
path('eid_collect_create/',views.EidCollectCreateView.as_view(),name='eid_collect_create'),

path('new_eid_list',views.NewEidListView.as_view(),name='new_eid_list'),
path('new_eid_print',views.NewEidPrint, name='new_eid_print'),
path('new_eid_detail/<str:pk>/',views.NewEidDetailView.as_view(),name='new_eid_detail'),
path('new_eid/update/<str:pk>/',views.NewEidUpdateView.as_view(),name='new_eid_update'),
path('new_eid/delete/<str:pk>/',views.NewEidDeleteView.as_view(),name='new_eid_delete'),
path('new_eid_create/',views.NewEidCreateView.as_view(),name='new_eid_create'),

path('upload-New-EID-csv/', views.neweid_upload, name="neweid_upload"),
path('upload-labour-contract-csv/', views.labourcontract_upload, name="labour_contract_upload"),
path('update-labour-contract-csv/', views.passport_update, name="passport_update"),

path('p_contract_sign',views.p_contract_sign, name='p_contract_sign'),
path('p_wp_sign',views.p_wp_sign, name='p_wp_sign'),
path('p_eid_collect',views.p_eid_collect, name='p_eid_collect'),
path('p_p_collect',views.p_p_collect, name='p_p_collect'),


path('p_passport_collect',views.p_passport_collect, name='p_passport_collect'),
path('p_visa_medical',views.p_visa_medical, name='p_visa_medical'),

path('passport_return_list',views.PassportReturnListView.as_view(),name='p_return_list'),

userapp/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from django.urls import reverse_lazy
from django.views.generic import (View, ListView, TemplateView, DetailView, CreateView, UpdateView, DeleteView)
from . import models
from . forms import EmployeeForm
import re, os
from datetime import date
from django.db.models import Sum, Avg, Max, Count, Min
from django.db.models.functions import Coalesce
from django.db.models import Value
from openpyxl import Workbook
from openpyxl.styles import colors, Color, Border, Side, PatternFill, Font, GradientFill, Alignment
from os import path
from django.http import HttpResponse
from easy_pdf.views import PDFTemplateView, PDFTemplateResponseMixin, TemplateResponseMixin
from easy_pdf.rendering import render_to_pdf_response
from django.contrib import messages
import csv, io
from django.core.mail import send_mail, EmailMessage
from django.conf import settings
from django.http import FileResponse
from django.http import Http404
from django.views.generic.detail import BaseDetailView
from django.contrib import admin
from django.contrib.auth.models import User
from django.contrib.auth.admin import UserAdmin

# Create your views here.

def IndexView(request):
    return render(request, 'userapp/index.html')

def ProfileView(request):
    emp = models.Employee.objects.get(email=request.user.email)
    payslip = models.Payslip.objects.get(employee_id=emp.employee_id)
    record = models.Report.objects.filter(employee_id=emp.employee_id)
    add = models.Additionalpay.objects.filter(payslip__employee_id=emp.employee_id)
    deduction = models.Deduction.objects.filter(payslip__employee_id=emp.employee_id)
    timesheet = models.ReportTimesheet.objects.filter(report__employee_id=emp.employee_id)
    empid = emp.employee_id

    return render(request, 'userapp/user_profile.html',
        {'record':record,
        'empid':empid,
        'add':add,
        'deduction':deduction,
        'timesheet':timesheet,
        'emp':emp,
        'payslip':payslip
        })

class DepartmentListView(ListView):
    template_name = 'userapp/department_list.html'
    context_object_name = 'department_list'
    model = models.Department

    def get_context_data(self, *args, **kwargs):
        context = super(DepartmentListView,self).get_context_data(*args,**kwargs)
        dep_list = context['department_list']
        empData = []
        for dep in dep_list:
            total_em = models.Employee.objects.filter(department=dep).count()
            department_head = None
            try:
                department_head = models.Employee.objects.get(department_head=True, department=dep)
            except models.Employee.DoesNotExist:
                department_head = "-"
            total_emp = total_em or 0
            empData.append([dep,total_emp,department_head])
        context['Data'] = empData

        return (context)

def ListofEmpInDep(request, pk):
    data = models.Department.objects.get(pk=pk)
    list_employee = models.Employee.objects.filter(department=data)

    return render(request,'userapp/empdeplist.html',
        {'list_employee':list_employee,
        'data': data,
        })

def SalaryRecordDetail(request,empid ):
    fullname = models.Employee.objects.get(employee_id=empid)
    record = models.Report.objects.filter(employee_id=empid)
    add = models.Additionalpays.objects.filter(report__employee_id=empid)
    deduction = models.Deductions.objects.filter(report__employee_id=empid)
    timesheet = models.ReportTimesheet.objects.filter(report__employee_id=empid)
    data = []
    total_lwop = 0
    total_gross = 0
    total_add = 0
    total_ded = 0
    total_net = 0

    for r in record:
        empAdd = models.Additionalpays.objects.filter(report=r).aggregate(Sum('amount'))['amount__sum']
        empDed = models.Deductions.objects.filter(report=r).aggregate(Sum('amount'))['amount__sum']
        empAdd = empAdd or 0
        empDed = empDed or 0
        empAdd = (round(empAdd,2))
        empDed = (round(empDed,2))
        gross = r.gross_pay - r.lowp_deduction
        net= gross + empAdd - empDed

        total_lwop += r.lowp_deduction
        total_gross += gross
        total_add += empAdd
        total_ded += empDed
        total_net += net

        data.append([r,empAdd,empDed,net,gross])



    return render(request, 'userapp/salary_record_detail.html',
        {'record':record,
        'empid':empid,
        'add':add,
        'deduction':deduction,
        'timesheet':timesheet,
        'fullname':fullname,
        'data':data,
        'total_lwop':total_lwop,
        'total_gross': total_gross,
        "total_add": total_add,
        'total_ded': total_ded,
        'total_net': total_net,
        })


class EmployeeUpdateView(UpdateView):
    model = models.Employee
    form_class = EmployeeForm
    template_name='userapp/employee_update.html'

payroll/templates/payroll/employee_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="jumbotron shadow-sm p-3 mb-5 rounded mt-3">
  <h2 class="display-4"> Nurses list</h2>
  <a class="btn btn-outline-info btn-lg mb-2" href="{% url 'payroll:employee_create' %}" role="button"><i class="fas fa-user-plus"> </i> Add new nurse</a>
  <a class="btn btn-outline-primary btn-lg mb-2" href="{% url 'payroll:employee_upload' %}">Bulk nurses Upload</a>
  <a class="btn btn-outline-primary btn-lg mb-2" href="{% url 'payroll:employee_update' %}">Bulk Update employee upload</a>
  <a class="btn btn-outline-danger btn-lg mb-2" href="{% url 'payroll:employee_export' %}">Employee Export</a>
  
  
  <div class="form-group row m-3">
    <form class="form-inline" action="" method="get">
    <input class="form-control" type="text" name="employeeid" id="employeeid" placeholder="Employee ID">
    <div class="input-group">
        <select class="custom-select" name="hotel" id="inputGroupSelect04">
            <option value=""> Select Hotel</option>                 
            {% for pay in hotel %}                   
                <option value="{{pay.pk}}"> {{pay}} </option>
            {% endfor %}            
        </select>            
    </div>
    <div class="input-group">
      <select class="custom-select" name="status" id="status">
          <option value=""> Employee Status</option>                 
          {% for sta in status %}                   
              <option value="{{sta}}"> {{sta}} </option>
          {% endfor %}            
      </select>            
  </div>
     <button type="submit" class="btn btn-primary ml-1">Search</button>
    </form>
</div>


  <table class="table table-hover h-100 p-3" id="table_id" class="dispaly">
    <thead>
      <tr>
        <th scope="col">SN</th>
        <!-- <th scope="col">Image</th> -->
        <th scope="col">Employee ID</th>
        <th scope="col">Name</th>
        <th scope="col">Phone</th>
        <th scope="col">Hotel</th>
        <!-- <th scope="col">Department</th> -->
        <th scope="col">Designation</th>
        <th scope="col">Status</th>
        <th scope="col">Edit</th>
      </tr>
    </thead>
    <tbody>
      {% for employee in employee_list %}
      <tr>
        <td scope="row">{{ forloop.counter }}</td>
        <!-- <td> <a href="{{employee.img.url}}"> <img src="{{employee.img.url}}" width="30" alt=""></a> </td> -->
        <td> {{employee.employee_id }}</td>
        <td> <a href="{% url 'payroll:employee_detail' pk=employee.pk %}">{{employee.first_name}} {{employee.last_name | default:""}}
            {% if employee.department_head == True %}
            <i class="far fa-star"></i>
            {% endif %}
        </td>
        <td> {{employee.phone }}</td>
        <td> {{employee.hotel }}</td>
        <!-- <td> {{employee.department }}</td> -->
        <td> {{employee.designation }}</td>
        <td> {{employee.employee_status }}</td>
        <td> <a href="{% url 'payroll:employee_update' pk=employee.pk %}"><i class="fas fa-edit"> </a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}
{% block script %}
<script>
  $(document).ready(function() {
    $('#table_id').DataTable();
  });
</script>
{% endblock %}

payroll/templates/payroll/payroll_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% load humanize %}
<div class="jumbotron mt-3">
  <h1 class="display-4 mb-3">Paid payroll detail</h1>

  <a class="btn btn-outline-info btn-lg mb-2" href="{% url 'payroll:downloadAll' pk=data.payroll_id %}" role="button"> Download all Payslips <i class="fas fa-download ml-2 mr-2 "> </i> </a>
  <a class="btn btn-outline-info btn-lg mb-2" href="{% url 'payroll:email' pk=data.payroll_id %}" role="button"> Send all Payslip <i class="fas fa-paper-plane ml-2 mr-2 "></i></a>
  <!-- <a class="btn btn-outline-info btn-lg mb-2" href="#" role="button"> Send email</a> -->
  

  <div class="row">
    <div class="col-sm-12 col-md-6 process-detail">
      <ul class="list-group">
        <li class="list-group-item">Payroll ID : {{data.payroll_id }}</li>
        <li class="list-group-item">Salary Month : {{data.salary_month}}</li>
        <li class="list-group-item">Salary Type : {{data.salary_type }}</li>
        <li class="list-group-item">Status : {{data.status }}</li>
      </ul>
    </div>
    <div class="col-sm-12 col-md-6 ">
      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle float-right" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Take Actions
        </button>
        <div class="dropdown-menu mr-5" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="{% url 'payroll:excle' pk=data.pk %}"> <i class="fas fa-file-excel ml-2 mr-2"> </i>Master Excle</a>
          <a class="dropdown-item" href="{% url 'payroll:pays_detail_pdf_list' pk=data.pk %}"> <i class="fas fa-download ml-2 mr-2 "> </i> Pay details</a>
          <a class="dropdown-item" href="{% url 'payroll:salary_additional' pk=data.pk %}"><i class="fas fa-plus-circle ml-2 mr-2"> </i> Additional pay details</a>
          <a class="dropdown-item" href="{% url 'payroll:salary_deductions' pk=data.pk %}"><i class="fas fa-minus-circle ml-2 mr-2"> </i> Deductions details</a>
          <a class="dropdown-item" href="{% url 'payroll:emp_timesheet' pk=data.pk %}"><i class="far fa-calendar-times ml-2 mr-2"></i> Timesheet details</a>
          <a class="dropdown-item" href="{% url 'payroll:email' pk=data.payroll_id %}"><i class="fas fa-paper-plane ml-2 mr-2 "></i>Send bulk payslip</a>
        </div>
      </div>
    </div>
  </div>
  <hr>
  <table class="table table-hover shadow h-100 p-3 mb-3" id="table_id">
    <thead>
      <tr>
        <th scope="col">SN.</th>
        <th scope="col">Employee</th>
        <!-- <th scope="col">Gross</th> -->
        <th scope="col">Gross</th>
        <th scope="col">Additional</th>
        <th scope="col">Deduction</th>
        <th scope="col">LWOP</th>
        <th scope="col">Net Pay</th>
        <th scope="col">View Report</th>
      </tr>
    </thead>
    <tbody>
      {% for emp in empData%}
      <tr>
        <td scope="row">{{ forloop.counter }}</td>
        <td> {{ emp.0.full_name }}</td>
        <!-- <td> {{ emp.2|intcomma }}</td> -->
        <td> {{ emp.6|intcomma }}</td>
        <td> {{ emp.3|intcomma }}</td>
        <td> {{ emp.4|intcomma }}</td>
        <td> ( {{ emp.7|intcomma }} )</td>
        <td> {{ emp.5|intcomma }}</td>
        <td>
          <!-- <a href="{% url 'payroll:payroll_report_view' payrollid=data.payroll_id empid=emp.1 %}">
            <i class="fa fa-eye"></i>
          </a> | -->
          <a href="{% url 'payroll:payroll_report' payrollid=data.payroll_id empid=emp.1 %}"><i class="fa fa-eye"></i></a> |
          <!-- <a href="{% url 'payroll:pdf' pk=data.payroll_id empid=emp.1 %}"><i class="fa fa-file-pdf"></i></a> | -->
          <a href="{% url 'payroll:displayPdf' pk=data.payroll_id empid=emp.1 %}"><i class="fa fa-file-pdf"></i></a> |
          <a href="{% url 'payroll:emailpdf' pk=data.payroll_id empid=emp.1 %}"><i class="fas fa-paper-plane"></i></a>
         
        </td>
      </tr>
      {% endfor %}
      <thead>
        <tr>
          <th scope="col">Total</th>
          <th scope="col"> {{ empCount }} </th>
          <th scope="col"> {{ total_gross|intcomma }}</th>
          <!-- <th scope="col"> {{ total_actual_gross }}</th> -->
          <th scope="col"> {{ total_add|intcomma }}</th>
          <th scope="col"> {{ total_ded|intcomma }}</th>
          <th scope="col"> ( {{ total_lwop|intcomma }} )</th>
          <th scope="col"> {{ total_net|intcomma}}</th>
          <th scope="col"> </th>
        </tr>
      </thead>
    </tbody>
  </table>
  <a class="btn btn-outline-danger btn-lg mt-3" href="{% url 'payroll:payroll_register' %}" role="button">Back to payroll list</a>
</div>
{% endblock %}
{% block script %}
<script>
  $(document).ready(function() {
    $('#table_id').DataTable();
  });
</script>
{% endblock %}

payroll/templates/payroll/payroll_register_list.html
{% extends "base.html" %}
{% block content %}
{% load humanize %}
<p></p>
<div class="jumbotron">
  <h1 class="display-4 mb-3">Payroll register</h1>
  <div class="card mb-5">
    <h5 class="card-header">Payroll processing</h5>
    <div class="card-body">
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">SN.</th>
            <th scope="col">Payroll ID</th>
            <th scope="col">Pay Month</th>
            <th scope="col">Pay Nos.</th>
          </tr>
        </thead>
        <tbody>
          {% for pay in processing_data %}
          <tr>
            <td scope="row">{{ forloop.counter }}</td>
            <td scope="row"> <a href="{% url 'payroll:process_salary_detail' pk=pay.0.pk %}">
                {{ pay.0.payroll_id }} </a></td>
            <td scope="row">{{ pay.0.salary_month | date:'M-Y'}}</td>
            <td scope="row"> {{pay.1}}</td>
            {% endfor %}
        </tbody>
      </table>
      <a class="btn btn-outline-info btn-lg mb-2" href="{% url 'payroll:process_salary_create' %}" role="button">Process new payroll</a>
    </div>
  </div>
  <div class="card mb-5">
    <h5 class="card-header">Paid payroll</h5>
    <div class="card-body">
      <table class="table table-hover h-100 p-3" id="table_id" class="dispaly">
        <thead>
          <tr>
            <th scope="col">SN.</th>
            <th scope="col">Payroll ID</th>
            <th scope="col">Pay Month</th>
            <th scope="col">Pay Nos.</th>
            <!-- <th scope="col">G.Pay</th> -->
            <th scope="col"> Gross Pay</th>
            <th scope="col">Additional</th>
            <th scope="col">Deduction</th>
            <th scope="col">Net Pay</th>
          </tr>
        </thead>
        <tbody>
          {% for pay in paid_data %}
          <tr>
            <td scope="row">{{ forloop.counter }}</td>
            <td scope="row"> <a href="{% url 'payroll:payroll_detail' pk=pay.0.pk %}">
                {{ pay.0.payroll_id }} </a></td>
            <td scope="row"> {{ pay.0.salary_month | date:'M-Y' }}</td>
            <td scope="row"> {{pay.0.employee_count}}</td>
            <!-- <td scope="row">{{ pay.0.gross_pay|intcomma}}</td> -->
            <td scope="row">{{ pay.0.actual_gross_pay|intcomma}}</td>
            <td scope="row">{{ pay.0.Additional_pay|intcomma}}</td>
            <td scope="row">{{ pay.0.deduction|intcomma}}</td>
            <td scope="row">{{ pay.0.total|intcomma}}</td>
            {% endfor %}
        </tbody>
        <tr>
          <th scope="col">Total</th>
          <th scope="col"></th>
          <th scope="col"></th>
          <th scope="col"></th>
          <!-- <th scope="col">{{calc_data.0|intcomma}}</th> -->
          <th scope="col">{{calc_data.4|intcomma}}</th>
          <th scope="col">{{calc_data.1|intcomma}}</th>
          <th scope="col">{{calc_data.2|intcomma}}</th>
          <th scope="col">{{calc_data.3|intcomma}}</th>
        </tr>
      </table>
    </div>
  </div>
</div>
{% endblock %}
{% block script %}
<script>
  $(document).ready(function() {
    $('#table_id').DataTable();
  });
</script>
{% endblock %}